[workspace]
resolver = "1"
members = ["quotes", "server"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
rand = "0"
crossbeam = "0"
clap = { version = "4", features = ["derive"] }